### ISSUE TITLE
Use viewer.layers.events for event callback

### ISSUE THREAD

**Issue by gselzer** [sylvainprigent/napari-stracking#4]
The call to `napari_viewer.events.layers_change.connect(self._on_layer_change)` ([here](https://github.com/sylvainprigent/napari-stracking/blob/a4a1e170bb54f6567c211de6562a0b7f4f9b7974/napari_stracking/_sfeatures_workers.py#LL21C58-L21C58)) is deprecated - I get the warning

```
/home/gselzer/mambaforge/envs/napari-imagej-dev/lib/python3.10/site-packages/napari_stracking/_sfeatures_workers.py:20: FutureWarning: This event will be removed in 0.5.0. Please use viewer.layers.events instead!
```
0.5.0 is close, I think - we should update to use `viewer.layers.events`!

**Comment by sylvainprigent** [comment]
Thanks for point it. It has been fixed in version 0.1.10
